controllers:
    resource:
        path: ../src/User/Presentation/Controller/
        namespace: App\User\Presentation\Controller
    type: attribute


api_auth_login:
    path: /api/auth/login
    methods: [POST]

